spring.application.name=back

#graphid => My-Graph-5pnvxc
apollo.key=service:My-Graph-5pnvxc:aEOglIDksqkux_NeX1g2BA
apollo.graph.ref=My-Graph-5pnvxc@current

# WSOCKET
spring.graphql.websocket.path=/graphql

#CORS NEXTJS
spring.web.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000
spring.web.cors.allowed-methods=GET,POST
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

#JWT CONFIG
jwt.secret=iOoeukdAoL5Y5naqKWragV66UMxVr9h5LQJK7zLpOUO

#POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tasksync
spring.datasource.username=postgres
spring.datasource.password=daniloospina7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#http cokies
server.servlet.session.cookie.http-only=true

# GraphQL Interfaz
spring.graphql.graphiql.enabled=true
spring.graphql.voyager.enabled=true
spring.graphql.schema.introspection.enabled=true


#Scalars
graphql.datetime.scalars.local-date-time.format=yyyy-MM-dd'T'HH:mm:ss
graphql.datetime.scalars.zone-conversion-enabled=true
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false