spring.application.name=back

#graphid => My-Graph-5pnvxc
apollo.key=service:My-Graph-5pnvxc:aEOglIDksqkux_NeX1g2BA
apollo.graph.ref=My-Graph-5pnvxc@current

# WSOCKET
spring.graphql.websocket.path=/graphql

#CORS NEXTJS
spring.web.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000
spring.web.cors.allowed-methods=GET,POST
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

#JWT CONFIG
jwt.secret=iOoeukdAoL5Y5naqKWragV66UMxVr9h5LQJK7zLpOUO

#POSTGRESQL
# => esta es la de AWS RDS la de abajo
#spring.datasource.url=jdbc:postgresql://tasksync.cl2e2ikiydbm.us-east-2.rds.amazonaws.com:5432/tasksync
spring.datasource.url=jdbc:postgresql://postgres:5432/tasksync
spring.datasource.username=postgres
spring.datasource.password=daniloospina7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#http cokies
server.servlet.session.cookie.http-only=true

# GraphQL Interfaz
spring.graphql.graphiql.enabled=true
spring.graphql.voyager.enabled=true
spring.graphql.schema.introspection.enabled=true


#S3 CONFIG
aws.access-key=${aws_access_key}
aws.secret-key=${aws_secret_key}
aws.region=${aws_region}
aws.s3.bucket=${aws_s3_bucket}


#Scalars
graphql.datetime.scalars.local-date-time.format=yyyy-MM-dd'T'HH:mm:ss
graphql.datetime.scalars.zone-conversion-enabled=true
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false


#Resend -> Emails
resend.token=re_iXnTvhfW_95MszmbmNKZER5f5TWzxLKEV
resend.email.to=daniloospina40@gmail.com

#NNEXT EMAIL CONF
app.frontend.url=http://localhost:3000


#Email STMP config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daniloospina40@gmail.com
spring.mail.password=ijhp kkdd imnv fiux
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Redis Docker config
spring.data.redis.host=redis
spring.data.redis.port=6379
